name=' vishwa s appaji '
name1="VISHWA S APPAJI"
print(name.upper())
print(name.lower())
print(name.strip())
print(name.replace('a','b'))
print(name.split(" "))
age=21
txt="my name is"+name+"age is {} and pin code is {}"
print(txt.format(age,587125))
newTxt="I am {2} from {0} aged {1}"
print(newTxt.format(587125,21,"Vishwa"))
print("hello's world")
print('"Hello world"')

#string methods
print('The string methods'.center(100,'='))
print(name.capitalize())
print(name.casefold())
print("centers the string".center(100,"="))
print(name.upper())
print(name1.lower())
print("My name is Ståle".encode(encoding="ascii",errors="backslashreplace"))
print("My name is Ståle".encode(encoding="ascii",errors="ignore"))
print("My name is Ståle".encode(encoding="ascii",errors="replace"))
print("My name is Ståle".encode(encoding="ascii",errors="namereplace"))
# print("My name is Ståle".encode(encoding="ascii",errors="strict")) throws error as some characters cannot be encoded so commented
print("65 66 67".encode(encoding="ascii",errors="backslashreplace"))
print(name.endswith('a'))
print(name.count('a'))
print(name.expandtabs())
print(name.find('i'))
print(name.find('p'))
print("String format() examples".center(105,"="))
# print("The price of the object is {price:.2f}".format(money=29))#gives us error as key value doesnt match
print("The price of the book is {price:.2f}".format(price=12334))
print("My name is {name} from {school}".format(school="VIT",name="Vishwa"))
print("we have {number:<10} chickens".format(number=30))
print("we have {:>10} chickens".format(30))
print("we have {:^20} chickens".format(30))
print("we have {:=4} chickens".format(30))
print("we have {:+10} chickens".format(30))
print("we have {:,} chickens".format(300000))
print("we have {:_} chickens".format(300000))
print("we have {:b} chickens".format(30))
print("we have {:c} chickens".format(30))
print("we have {:e} chickens".format(30))
print("we have {:E} chickens".format(30))
print("we have {:o} chickens".format(30))
print("we have {:x} chickens".format(30))
print("we have {:X} chickens".format(30))
print("we have {:%} chickens".format(30))

print(name.index("p"))
print(name.isalnum())
print(name.isalpha())
print(name.isdigit())
print(name.isascii())
print(name.isdecimal())
print(name.isnumeric())
print(name.islower())
print(name.isidentifier())
print(name.ljust(10))
print(name.lstrip())
print(name.partition('s'))
print(name.find('s'))
print(name.index('s'))
print(name.rfind('s'))
print(name.rindex('s'))
print(name.rpartition('s'))
print(name.rsplit(" ",2))
print(name.split(" ",2))
print(name.swapcase())
print(name.title())

tempTxt='i want {0} pieces of {1} priced at {2:.2f}'
print(tempTxt.format(2,'chicken',12.234))
school='Sainik school kodagu'
# print('i studied in ')